name: unleashedrecomp
base: core24
version: '1.0.3-1'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: Static recompilation of Sonic Unleashed.
description: |
  An unofficial PC port of the Xbox 360 version of Sonic Unleashed created through the process of static recompilation. 
grade: stable
confinement: strict
icon: UP_Mod-icon.png

apps:
  unleashedrecomp:
    command: UnleashedRecomp --sdl-video-driver wayland
    desktop: io.github.hedge_dev.unleashedrecomp.desktop
    common-id: io.github.hedge_dev.unleashedrecomp
    environment:
      HOME: $SNAP_USER_COMMON
    extensions: [kde-neon-6]
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez

parts:
  unleashedrecomp:
    plugin: dump
    source: https://github.com/Jujstme/UnleashedRecomp/releases/download/$SNAPCRAFT_PROJECT_VERSION/UnleashedRecomp-$SNAPCRAFT_PROJECT_VERSION.zip
    prime:
      - UnleashedRecomp

  dot-desktop:
    after: [unleashedrecomp]
    plugin: dump
    source: ./dot-desktop
    prime:
      - io.github.hedge_dev.unleashedrecomp.desktop